// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/get-involved": {
    params: {};
  };
  "/knowledge-transfer": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/news": {
    params: {};
  };
  "/admin/services": {
    params: {};
  };
  "/admin/testimonial": {
    params: {};
  };
  "/admin/knowledgeT": {
    params: {};
  };
  "/admin/register": {
    params: {};
  };
  "/admin/profile": {
    params: {};
  };
  "/admin/training": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/get-involved" | "/knowledge-transfer" | "/news" | "/products" | "/services" | "/register" | "/admin" | "/admin/dashboard" | "/admin/news" | "/admin/services" | "/admin/testimonial" | "/admin/knowledgeT" | "/admin/register" | "/admin/profile" | "/admin/training";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/get-involved.tsx": {
    id: "routes/get-involved";
    page: "/get-involved";
  };
  "routes/knowledge-transfer.tsx": {
    id: "routes/knowledge-transfer";
    page: "/knowledge-transfer";
  };
  "routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/dashboard" | "/admin/news" | "/admin/services" | "/admin/testimonial" | "/admin/knowledgeT" | "/admin/register" | "/admin/profile" | "/admin/training";
  };
  "routes/admin.dashboard.tsx": {
    id: "routes/admin.dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin.news.tsx": {
    id: "routes/admin.news";
    page: "/admin/news";
  };
  "routes/admin.services.tsx": {
    id: "routes/admin.services";
    page: "/admin/services";
  };
  "routes/admin.testimonial.tsx": {
    id: "routes/admin.testimonial";
    page: "/admin/testimonial";
  };
  "routes/admin.knowledgeT.tsx": {
    id: "routes/admin.knowledgeT";
    page: "/admin/knowledgeT";
  };
  "routes/admin.register.tsx": {
    id: "routes/admin.register";
    page: "/admin/register";
  };
  "routes/admin.profile.tsx": {
    id: "routes/admin.profile";
    page: "/admin/profile";
  };
  "routes/admin.training.tsx": {
    id: "routes/admin.training";
    page: "/admin/training";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/get-involved": typeof import("./app/routes/get-involved.tsx");
  "routes/knowledge-transfer": typeof import("./app/routes/knowledge-transfer.tsx");
  "routes/news": typeof import("./app/routes/news.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin.dashboard": typeof import("./app/routes/admin.dashboard.tsx");
  "routes/admin.news": typeof import("./app/routes/admin.news.tsx");
  "routes/admin.services": typeof import("./app/routes/admin.services.tsx");
  "routes/admin.testimonial": typeof import("./app/routes/admin.testimonial.tsx");
  "routes/admin.knowledgeT": typeof import("./app/routes/admin.knowledgeT.tsx");
  "routes/admin.register": typeof import("./app/routes/admin.register.tsx");
  "routes/admin.profile": typeof import("./app/routes/admin.profile.tsx");
  "routes/admin.training": typeof import("./app/routes/admin.training.tsx");
};