// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/knowledge-transfer": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/get-involved": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/products" | "/services" | "/knowledge-transfer" | "/news" | "/get-involved";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/knowledge-transfer.tsx": {
    id: "routes/knowledge-transfer";
    page: "/knowledge-transfer";
  };
  "routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "routes/get-involved.tsx": {
    id: "routes/get-involved";
    page: "/get-involved";
  };
};